# Generated by Django 2.2.4 on 2019-08-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=250)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_finished', models.DateField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
