# Generated by Django 2.2.4 on 2019-08-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='date_finished',
        ),
    ]
